name: PR workflow

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  link-issue:
    runs-on: ubuntu-latest
    steps:
      - uses: PieterT2000/gh-housekeeping@latest
        with:
          task: link-issue
          token: ${{ secrets.GITHUB_TOKEN }}
