name: PR

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  link-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: PieterT2000/gh-housekeeping@latest
        with:
          task: autolink-issue
          token: ${{ secrets.GITHUB_TOKEN }}
